In [39]:
import numpy as np

In [40]:
a=np.array([0,1,2])
b=np.array([5,5,5])
a+b

array([5, 6, 7])

In [41]:
a+5

array([5, 6, 7])

In [42]:
M=np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [45]:
a=np.arange(3)
b=np.arange(3)[:,np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [46]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

规则1：如果两个数组的维度数不同，则维度较小的数组将在其左侧填充shape。

规则2：如果两个数组在任何维度上都不匹配，则shape等于1的数组将被拉伸以匹配其他shape。

规则3：如果在任何维度中，大小不一致且都不等于1，则会引发错误。

In [47]:
M=np.ones((2,3))
a=np.arange(3)

In [48]:
print(M.shape)
print(a.shape)

(2, 3)
(3,)


In [49]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [50]:
a=np.arange(3).reshape(3,1)
b=np.arange(3)

In [51]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [52]:
M=np.ones((3,2))
a=np.arange(3)

In [53]:
print(M.shape)
print(a.shape)

(3, 2)
(3,)


a->(1,3)

In [54]:
M+a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [55]:
a[:,np.newaxis].shape

(3, 1)

In [57]:
M+a[:,np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

In [58]:
np.logaddexp(M,a[:,np.newaxis])

array([[1.31326169, 1.31326169],
       [1.69314718, 1.69314718],
       [2.31326169, 2.31326169]])

In [59]:
X=np.random.random((10,3))
X

array([[0.49723813, 0.62129082, 0.83330836],
       [0.3455888 , 0.72685558, 0.12127381],
       [0.04417115, 0.31301621, 0.43786933],
       [0.59827588, 0.8744778 , 0.37929103],
       [0.6043821 , 0.53430831, 0.15550965],
       [0.5711754 , 0.04220066, 0.90385083],
       [0.11734098, 0.96550919, 0.00545939],
       [0.45341916, 0.07832587, 0.04543909],
       [0.83700949, 0.04861332, 0.54136204],
       [0.91182477, 0.50326215, 0.18870184]])

In [60]:
Xmean=X.mean(0)
Xmean

array([0.49804259, 0.47078599, 0.36120654])

In [61]:
X_centered=X-Xmean

In [62]:
X_centered

array([[-0.00080446,  0.15050483,  0.47210182],
       [-0.15245379,  0.25606959, -0.23993273],
       [-0.45387143, -0.15776978,  0.0766628 ],
       [ 0.10023329,  0.40369181,  0.0180845 ],
       [ 0.10633951,  0.06352232, -0.20569688],
       [ 0.07313281, -0.42858533,  0.54264429],
       [-0.38070161,  0.49472319, -0.35574714],
       [-0.04462342, -0.39246012, -0.31576745],
       [ 0.33896691, -0.42217267,  0.1801555 ],
       [ 0.41378218,  0.03247616, -0.1725047 ]])

In [63]:
X_centered.mean(0)

array([2.22044605e-17, 4.99600361e-17, 1.11022302e-17])