In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [4]:
x1=np.random.randint(10,size=6)
x1

array([5, 0, 3, 3, 7, 9])

In [5]:
x2=np.random.randint(10,size=(3,4))
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [6]:
x3=np.random.randint(10,size=(3,4,5))
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [7]:
print("x3 ndim:",x3.ndim)
print("x3 shape",x3.shape)
print("x3 size",x3.size)

x3 ndim: 3
x3 shape (3, 4, 5)
x3 size 60


In [8]:
print("dtype:",x3.dtype)

dtype: int64


In [9]:
print("itemsize:",x3.itemsize,"bytes")

itemsize: 8 bytes


In [10]:
print("itemsize:",x3.nbytes,"bytes")

itemsize: 480 bytes


In [11]:
x1[0]

5

In [12]:
x1[4]

7

In [13]:
x1[-1]

9

In [14]:
x1[-2]

7

In [15]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [16]:
x2[0,0]

3

In [17]:
x2[2,0]

1

In [18]:
x2[2,-1]

7

In [19]:
x2[0,0]=12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [20]:
x2[0,0]=3.14159

In [21]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [23]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x[:5]

array([0, 1, 2, 3, 4])

In [25]:
x[5:]

array([5, 6, 7, 8, 9])

In [29]:
x[4:7]

array([4, 5, 6])

In [30]:
x[::2]

array([0, 2, 4, 6, 8])

In [31]:
x[::3]

array([0, 3, 6, 9])

In [32]:
x[1::2]

array([1, 3, 5, 7, 9])

In [33]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [34]:
x[5::-2]

array([5, 3, 1])

In [35]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [36]:
x2[:2,:3]

array([[3, 5, 2],
       [7, 6, 8]])

In [37]:
x2[::-1,::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [38]:
print(x2[:,0])

[3 7 1]


In [39]:
print(x2[0,:])

[3 5 2 4]


In [40]:
print(x2[0])

[3 5 2 4]


In [41]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [42]:
x2_sub=x2[:2,:2]

In [43]:
x2_sub

array([[3, 5],
       [7, 6]])

In [44]:
x2_sub[0,0]=99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [45]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [46]:
x2_sub_copy=x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [47]:
x2_sub_copy[0,0]=42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [48]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [49]:
grid=np.arange(1,10).reshape(3,3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [51]:
x.reshape((1,3))

array([[1, 2, 3]])

In [52]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [53]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [54]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [55]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [56]:
z=[4,5,6]

In [57]:
print(np.concatenate([x,y,z]))

[1 2 3 3 2 1 4 5 6]


In [58]:
x=[1,2,3,99,100,3,2,1]
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [ 99 100] [3 2 1]
