In [2]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output=np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/values[i]
    return output

values=np.random.randint(1,10,size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [3]:
big_array=np.random.randint(1,100,size=1000000)
%timeit compute_reciprocals(big_array)

2.64 s ± 16.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
print(compute_reciprocals(values))
print(1.0/values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [6]:
%timeit (1.0/big_array)

3.57 ms ± 41 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [9]:
x=np.arange(9).reshape(3,3)
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [10]:
x=np.arange(4)
x

array([0, 1, 2, 3])

In [11]:
x+5

array([5, 6, 7, 8])

In [12]:
x-5

array([-5, -4, -3, -2])

In [13]:
x*2

array([0, 2, 4, 6])

In [14]:
x/2

array([0. , 0.5, 1. , 1.5])

In [15]:
x//2

array([0, 0, 1, 1])

In [16]:
-x

array([ 0, -1, -2, -3])

In [17]:
x**2

array([0, 1, 4, 9])

In [18]:
x%2

array([0, 1, 0, 1])

In [19]:
-(0.5*x+1)**2

array([-1.  , -2.25, -4.  , -6.25])

In [20]:
np.add(x,2)

array([2, 3, 4, 5])

In [21]:
x=np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

In [22]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [23]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [24]:
x=np.array([3-4j,4-3j,2+0j,0+1j])
np.abs(x)

array([5., 5., 2., 1.])

In [25]:
theta=np.linspace(0,np.pi,3)

In [26]:
theta

array([0.        , 1.57079633, 3.14159265])

In [27]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [28]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [29]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [30]:
x=[-1,0,1]
x
np.arcsin(x)

array([-1.57079633,  0.        ,  1.57079633])

In [31]:
np.arccos(x)

array([3.14159265, 1.57079633, 0.        ])

In [32]:
np.arctan(x)

array([-0.78539816,  0.        ,  0.78539816])

In [34]:
x=[1,2,3]
x
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [35]:
np.exp2(x)

array([2., 4., 8.])

In [39]:
np.power(3,x)

array([    3,     9,    81, 59049])

In [40]:
x=[1,2,4,10]
x
np.log(x)

array([0.        , 0.69314718, 1.38629436, 2.30258509])

In [41]:
np.log2(x)

array([0.        , 1.        , 2.        , 3.32192809])

In [42]:
np.log10(x)

array([0.        , 0.30103   , 0.60205999, 1.        ])

In [43]:
x=np.arange(1,6)
np.add.reduce(x)

15

In [44]:
np.multiply.reduce(x)

120

In [45]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [46]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [47]:
x=np.arange(1,6)
y=np.arange(1,5)
np.multiply.outer(x,y)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16],
       [ 5, 10, 15, 20]])